title: NDID platform
theme: jekyll-theme-primer
github:
  private: false
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/ndidplatform/ndidplatform.github.io"
google_analytics: UA-117150193-1
